eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8761/eureka/
  instance:
      prefer-ip-address: true
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}